backend:
  name: github
  repo: wj-quizzing/my-website
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Homepage"
        name: "home"
        fields:
          - label: "Content"
            name: "body"
            widget: "markdown"
